### ISSUE TITLE
Integrating enhancements back to upstream duckdb?

### ISSUE THREAD

**Issue by pankajp** [graindb/graindb#1]
I just stumbled upon this project which searching to optimize some queries with duckdb. Are there any plans to integrated these enhancements back to duckdb or has there been any conversations with the authors of duckdb?

xpost: https://github.com/duckdb/duckdb/discussions/2766

**Comment by ray6080** [comment]
Hi @pankajp ! Thanks for the interest in our project!
Currently this stays as an on-going research project and we're working on more research works. But yes, we do plan to talk to authors of DuckDB and integrate these ideas back to DuckDB.

**Comment by pankajp** [comment]
Thanks for sharing your thoughts and glad to know you have upstreaming in mind. There's some interesting work in this repo, though out of my level of understanding. I had stumbled upon https://arxiv.org/pdf/2108.10540.pdf and thought the performance numbers there are already significant to be useful for a wider community.
